/* 
* ======================================================================== 
* 
* Author：鼎燊文化传媒 Time：2015/4/7 10:48:30 
* File name：Config 
* Version：V1.0.1
* Company: 鼎燊文化传媒 
* Framework Version: 2.0
*
* ======================================================================== 
*/

using System;
using System.Collections.Generic;
using System.Text;

namespace DSCM.Backstage
{
    public class Config
    {
        public static string Admin_Navigation = "{ "
                            + "\"Navigation\": [ "
                            + "    {"
                            + "      \"title\": \"项目管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i1.gif\","
                            + "      \"type\": \"0\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"项目\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"项目列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=zc&cm=index\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "  },"
                            

                            + "    {"
                            + "      \"title\": \"用户管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i3.gif\","
                            + "      \"type\": \"1\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"用户管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"用户列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=user&cm=index\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "  },"



                            + "    {"
                            + "      \"title\": \"评论管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i4.gif\","
                            + "      \"type\": \"2\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"评论管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"项目评论列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=zc&cm=com\""
                            + "                    },"
                            + "                    {"
                            + "                       \"title\": \"日志评论列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=user&cm=logcom\""
                            + "                    },"
                            + "                    {"
                            + "                       \"title\": \"相册评论列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=user&cm=photocom\""
                            + "                    },"
                            + "                    {"
                            + "                       \"title\": \"留言列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=user&cm=mes\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "  },"



                            + "    {"
                            + "      \"title\": \"订单管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i2.gif\","
                            + "      \"type\": \"3\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"订单管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"订单列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=order&cm=index\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "    },"



                            + "    {"
                            + "      \"title\": \"新闻管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i6.gif\","
                            + "      \"type\": \"4\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"新闻管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"新闻列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=new&cm=index\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "    },"



                            + "    {"
                            + "      \"title\": \"标签通知管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i6.gif\","
                            + "      \"type\": \"5\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"标签通知管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"标签列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=quanzi&cm=biaoqian\""
                            + "                    },"
                            + "                    {"
                            + "                       \"title\": \"通知类型列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=quanzi&cm=mesclass\""
                            + "                    },"
                            + "                    {"
                            + "                       \"title\": \"通知列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=quanzi&cm=message\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "    },"

                            + "    {"
                            + "      \"title\": \"系统设置\","
                            + "      \"img\": \"/backstage/resource/new/images/i7.gif\","
                            + "      \"type\": \"6\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"系统管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"管理员列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=admin&cm=index\""
                            + "                    },"
                            + "                    {"
                            + "                       \"title\": \"日志管理\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=log\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "    }"

                            + "  ]"
                            + "}";





        public static string Admin_Agent = "{ "
                            + "\"Navigation\": [ "
                            + "    {"
                            + "      \"title\": \"项目管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i1.gif\","
                            + "      \"type\": \"0\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"项目\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"项目列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=zc&cm=index\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "  },"
                            + "    {"
                            + "      \"title\": \"用户管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i3.gif\","
                            + "      \"type\": \"1\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"用户管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"用户列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=user&cm=index\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "  },"




                            + "    {"
                            + "      \"title\": \"评论管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i4.gif\","
                            + "      \"type\": \"2\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"评论管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"项目评论列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=zc&cm=com\""
                            + "                    },"
                            + "                    {"
                            + "                       \"title\": \"日志评论列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=user&cm=logcom\""
                            + "                    },"
                            + "                    {"
                            + "                       \"title\": \"相册评论列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=user&cm=photocom\""
                            + "                    },"
                            + "                    {"
                            + "                       \"title\": \"留言列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=user&cm=mes\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "  },"



                            + "    {"
                            + "      \"title\": \"订单管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i2.gif\","
                            + "      \"type\": \"3\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"订单管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"订单列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=order&cm=index\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "    },"

                            
                            + "    {"
                            + "      \"title\": \"新闻管理\","
                            + "      \"img\": \"/backstage/resource/new/images/i6.gif\","
                            + "      \"type\": \"4\","
                            + "      \"menu\": ["
                            + "            {"
                            + "             \"title\": \"新闻管理\","
                            + "             \"url\": \"\","
                            + "              \"_menu\": ["
                            + "                    {"
                            + "                       \"title\": \"新闻列表\","
                            + "                        \"url\": \"/backstage/index.aspx?ds=new&cm=index\""
                            + "                    }"
                            + "               ]"
                            + "           }"
                            + "       ]"
                            + "    }"

                            + "  ]"
                            + "}";

    }
}
